### Get all sales
GET http://localhost:8080/Sales

### Get sale by id
GET http://localhost:8080/Sales/1

### Create sale
POST http://localhost:8080/Sales
Content-Type: application/json

{
  "date": "2024-12-30",
  "total": 100.50
}

### Update sale
PUT http://localhost:8080/Sales/1
Content-Type: application/json

{
  "date": "2024-12-30",
  "total": 100.50
}

### Delete sale by id
DELETE http://localhost:8080/Sales/2
